<?php

namespace AppBundle\Repository;

/**
 * carsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class carsRepository extends \Doctrine\ORM\EntityRepository
{
}
