<?php

namespace AppBundle\Repository;

/**
 * team_leadersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class team_leadersRepository extends \Doctrine\ORM\EntityRepository
{
}
